meta_product_name: "culture shot"
meta_title: "culture shot | Your Portal To The Countless Museums Of Berlin!"
meta_description: "culture shot | Find all museums of berlin in one spot."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
